### ISSUE TITLE
The theory of camembertQA

### ISSUE THREAD

**Issue by QIANQIAN201** [assisyoussef/CamemBERTQA#1]
Fristly I want to thank you for your great work about CamemBERT QA.

I have read your code:CamemBERT Final.ipynb, i found out that you used 'model_path = 'fmikaelian/camembert-base-fquad'. I kown it's a fine-tuned qa model based on dataset Fquad. But i don't understand well how to train a 'camembert-base' model for a qa task. Is the same principe like BERT for qa task? I will be very appreciated if you can share some articles/resources with me about the theory of CamemeBERT question-answer model. (Cause there existe few articles about CamemBERT model)

Wish you have a good day!

**Comment by youssefassis** [comment]
Hii,
Yeah it's exactly like CamemBERT model. You should just use the CamemBERT model as you starting point and then add a linear layer to generate the start and the end of the answer from the input paragraph.

For any further information, please do not hesitate to contact me.
